### ISSUE TITLE
Simplify: Apply shared CSS properties to multiple elements at once to simplify the code.

### ISSUE THREAD

**Issue by josephtkim** [asal4793/prj-rev-bwfs-dasmoto#5]
You can simplify your CSS code by applying shared properties to multiple elements at once rather than individually. For instance, properties like the font-family and font-weight are shared across all elements, so you can apply it to the entire page like
```css
html {
  font-family: Helvetica;
  font-weight: bold;
}
```
